Repository Azure/bicep, pull requests merged in 2023-10, with the labels that each got.

#11974 Undoing `validate-params` command PR
  src/Bicep.Cli.IntegrationTests/ValidateParamsCommandTests.cs
  src/Bicep.Cli/Arguments/ValidateParamsArguments.cs
  src/Bicep.Cli/Commands/ValidateParamsCommand.cs
  src/Bicep.Cli/Constants/CliConstants.cs
  src/Bicep.Cli/Helpers/ServiceCollectionExtensions.cs
  src/Bicep.Cli/Program.cs
  src/Bicep.Cli/Services/ArgumentParser.cs
  src/Bicep.Core/Diagnostics/DiagnosticBuilder.cs
Labels: story: bicep parameters

#11975 Enable supplemental params validation with `build-params` command
  src/Bicep.Cli.IntegrationTests/BuildParamsCommandTests.cs
  src/Bicep.Cli/Commands/BuildParamsCommand.cs
  src/Bicep.Cli/Services/CompilationService.cs
Labels: story: bicep parameters

#12026 CodeFix: Remove relative path prefix from types loading
  .vscode/launch.json
  src/Bicep.Core/TypeSystem/Az/OciAzTypeLoader.cs
Labels: story: dynamic type loading

#12057 Write "{}" for config (breaking change, 11482)
  src/Bicep.Core.UnitTests/Assertions/MockRegistryAssertions.cs
  src/Bicep.Core/Json/JsonElementFactory.cs
  src/Bicep.Core/Registry/OciModuleRegistry.cs
Labels: breaking change

#11744 REFACTOR: Separate artifact validation for providers and modules
  src/Bicep.Cli.IntegrationTests/RestoreCommandTests.cs
  src/Bicep.Core.UnitTests/Assertions/OciModuleRegistryAssertions.cs
  src/Bicep.Core.UnitTests/Registry/MockRegistryBlobClient.cs
  src/Bicep.Core.UnitTests/Registry/OciModuleRegistryTests.cs
  src/Bicep.Core.UnitTests/Utils/OciModuleRegistryHelper.cs
  src/Bicep.Core/Modules/BicepModuleMediaTypes.cs
  src/Bicep.Core/Modules/OciModuleArtifactResult.cs
  src/Bicep.Core/Registry/AzureContainerRegistryManager.cs
  src/Bicep.Core/Registry/DefaultArtifactRegistryProvider.cs
  src/Bicep.Core/Registry/InvalidArtifactException.cs
  src/Bicep.Core/Registry/InvalidModuleException.cs
  src/Bicep.Core/Registry/Oci/BicepMediaTypes.cs
  src/Bicep.Core/Registry/Oci/OciArtifactResult.cs
  src/Bicep.Core/Registry/Oci/OciProviderArtifactResult.cs
  src/Bicep.Core/Registry/OciArtifactRegistry.cs
  src/Bicep.LangServer.IntegrationTests/HoverTests.cs
  src/Bicep.LangServer/Completions/BicepCompletionProvider.cs
  src/Bicep.LangServer/Completions/ModuleReferenceCompletionProvider.cs
  src/Bicep.LangServer/Completions/PublicRegistryModuleMetadataProvider.cs
Labels: story: dynamic type loading

#12127 Implement provider declaration aliasing
  src/Bicep.Cli.IntegrationTests/BuildCommandTests.cs
  src/Bicep.Cli/Commands/PublishCommand.cs
  src/Bicep.Core.IntegrationTests/ExtensibilityTests.cs
  src/Bicep.Core.IntegrationTests/ImportTests.cs
  src/Bicep.Core.IntegrationTests/RegistryTests.cs
  src/Bicep.Core.Samples/DataSetsExtensions.cs
  src/Bicep.Core.Samples/Files/baselines/Modules_CRLF/child/folder with separate config/moduleWithAzImport.bicep
  src/Bicep.Core.UnitTests/BicepTestConstants.cs
  src/Bicep.Core.UnitTests/Configuration/ConfigurationManagerTests.cs
  src/Bicep.Core.UnitTests/Configuration/RootConfigurationTests.cs
  src/Bicep.Core.UnitTests/Diagnostics/ErrorBuilderTests.cs
  src/Bicep.Core.UnitTests/Diagnostics/LinterRuleTests/OutputsShouldNotContainSecretsRuleTests.cs
  src/Bicep.Core.UnitTests/Diagnostics/LinterRuleTests/UseRecentApiVersionRuleTests.cs
  src/Bicep.Core.UnitTests/Modules/OciArtifactModuleReferenceTests.cs
  src/Bicep.Core.UnitTests/Registry/ArtifactDispatcherTests.cs
  src/Bicep.Core.UnitTests/Registry/OciModuleRegistryTests.cs
  src/Bicep.Core.UnitTests/Syntax/ImportSpecificationTest.cs
  src/Bicep.Core.UnitTests/Utils/OciModuleRegistryHelper.cs
  src/Bicep.Core/Configuration/AnalyzersConfigurationExtensions.cs
  src/Bicep.Core/Configuration/ConfigurationManager.cs
  src/Bicep.Core/Configuration/ProviderAliasesConfiguration.cs
  src/Bicep.Core/Configuration/RootConfiguration.cs
  src/Bicep.Core/Configuration/bicepconfig.json
  src/Bicep.Core/Diagnostics/DiagnosticBuilder.cs
  src/Bicep.Core/Emit/CompileTimeImports/ImportClosureInfo.cs
  src/Bicep.Core/Emit/ScopeHelper.cs
  src/Bicep.Core/Modules/OciModuleReference.cs
  src/Bicep.Core/Navigation/IArtifactReferenceSyntax.cs
  src/Bicep.Core/Registry/ArtifactRegistry.cs
  src/Bicep.Core/Registry/ArtifactType.cs
  src/Bicep.Core/Registry/IArtifactDispatcher.cs
  src/Bicep.Core/Registry/IArtifactReferenceFactory.cs
  src/Bicep.Core/Registry/IArtifactRegistry.cs
  src/Bicep.Core/Registry/LocalModuleRegistry.cs
  src/Bicep.Core/Registry/ModuleDispatcher.cs
  src/Bicep.Core/Registry/ModuleDispatcherExtensions.cs
  src/Bicep.Core/Registry/Oci/OciArtifactReference.cs
  src/Bicep.Core/Registry/OciArtifactRegistry.cs
  src/Bicep.Core/Registry/TemplateSpecModuleRegistry.cs
  src/Bicep.Core/Semantics/Compilation.cs
  src/Bicep.Core/Semantics/ImportedSymbol.cs
  src/Bicep.Core/Semantics/WildcardImportSymbol.cs
  src/Bicep.Core/Syntax/CompileTimeImportDeclarationSyntax.cs
  src/Bicep.Core/Syntax/ImportSpecification.cs
  src/Bicep.Core/Syntax/ModuleDeclarationSyntax.cs
  src/Bicep.Core/Syntax/ProviderDeclarationSyntax.cs
  src/Bicep.Core/Syntax/TestDeclarationSyntax.cs
  src/Bicep.Core/Syntax/UsingDeclarationSyntax.cs
  src/Bicep.Core/Workspaces/SourceFileGroupingBuilder.cs
  src/Bicep.LangServer.IntegrationTests/HoverTests.cs
  src/Bicep.LangServer.IntegrationTests/Registry/ModuleRestoreSchedulerTests.cs
  src/Bicep.LangServer.UnitTests/BicepRegistryCacheRequestHandlerTests.cs
  src/Bicep.LangServer/Handlers/BicepDefinitionHandler.cs
  src/Bicep.LangServer/Handlers/BicepForceModulesRestoreCommandHandler.cs
  src/Bicep.LangServer/Handlers/BicepHoverHandler.cs
  src/Bicep.LangServer/Handlers/BicepRegistryCacheRequestHandler.cs
  src/vscode-bicep/schemas/bicepconfig.schema.json
Labels: story: dynamic type loading

#12212 Added ProviderRegistry Feature Flag
  src/Bicep.Core.UnitTests/Configuration/ConfigurationManagerTests.cs
  src/Bicep.Core.UnitTests/Features/FeatureProviderOverrides.cs
  src/Bicep.Core.UnitTests/Features/OverriddenFeatureProvider.cs
  src/Bicep.Core/Configuration/ExperimentalFeaturesEnabled.cs
  src/Bicep.Core/CoreResources.Designer.cs
  src/Bicep.Core/Features/FeatureProvider.cs
  src/Bicep.Core/Features/IFeatureProvider.cs
  src/vscode-bicep/schemas/bicepconfig.schema.json
Labels: story: external resource type loading

#12282 Rename `IAzResourceTypeLoader` and `IAzResourceTypeLoaderFactory` classes since they are not specific to AZ
  src/Bicep.Cli/Helpers/ServiceCollectionExtensions.cs
  src/Bicep.Core.IntegrationTests/Extensibility/TestExtensibilityNamespaceProvider.cs
  src/Bicep.Core.UnitTests/BicepTestConstants.cs
  src/Bicep.Core.UnitTests/Diagnostics/LinterRuleTests/LinterRuleTestsBase.cs
  src/Bicep.Core.UnitTests/IServiceCollectionExtensions.cs
  src/Bicep.Core.UnitTests/Mock/FakeResourceTypes.cs
  src/Bicep.Core.UnitTests/Utils/CompilationHelper.cs
  src/Bicep.Core.UnitTests/Utils/ServiceBuilderExtensions.cs
  src/Bicep.Core.UnitTests/Utils/TestTypeHelper.cs
  src/Bicep.Core/Semantics/Namespaces/DefaultNamespaceProvider.cs
  src/Bicep.Core/TypeSystem/Az/AzResourceTypeLoader.cs
  src/Bicep.Core/TypeSystem/Az/AzResourceTypeLoaderFactory.cs
  src/Bicep.Core/TypeSystem/Az/AzResourceTypeProvider.cs
  src/Bicep.Core/TypeSystem/Az/IAzResourceTypeLoaderFactory.cs
  src/Bicep.Core/TypeSystem/IResourceTypeLoader.cs
  src/Bicep.Core/TypeSystem/IResourceTypeLoaderFactory.cs
  src/Bicep.LangServer.IntegrationTests/InsertResourceCommandTests.cs
  src/Bicep.LangServer.UnitTests/BicepCompilationManagerHelper.cs
  src/Bicep.LangServer/Handlers/InsertResourceHandler.cs
  src/Bicep.LangServer/IServiceCollectionExtensions.cs
  src/Bicep.RegistryModuleTool/Extensions/IServiceCollectionExtensions.cs
  src/Bicep.Wasm/IServiceCollectionExtensions.cs
Labels: story: dynamic type loading

#12333 Added missing .resx change around new Provider Registry feature flag
  src/Bicep.Core/CoreResources.resx
Labels: story: external resource type loading
