Repository Azure/bicep, pull requests merged in 2025-05, with the labels that each got.

#16990 Add linter rule to warn on unused compile-time imports
  src/Bicep.Core.IntegrationTests/CompileTimeImportTests.cs
  src/Bicep.Core.Samples/Files/baselines/Imports_LF/main.diagnostics.bicep
  src/Bicep.Core.UnitTests/Diagnostics/LinterRuleTests/NoUnusedImportsRuleTests.cs
  src/Bicep.Core/Analyzers/Linter/Rules/NoUnusedImportsRule.cs
  src/Bicep.Core/Analyzers/Linter/Rules/NoUnusedRuleBase.cs
  src/Bicep.Core/CoreResources.Designer.cs
  src/Bicep.Core/CoreResources.resx
  src/Bicep.LangServer.IntegrationTests/CodeActionTests.cs
  src/vscode-bicep/schemas/bicepconfig.schema.json
Labels: 📘 Docs Required

#17152 Create PR Compliance workflow
  .github/PULL_REQUEST_TEMPLATE.md
  .github/workflows/pr-compliance
Labels: 📘 Docs Not Needed

#17143 Support snapshots via JSONRPC interface
  src/Bicep.Cli.IntegrationTests/JsonRpcCommandTests.cs
  src/Bicep.Cli.IntegrationTests/TestBase.cs
  src/Bicep.Cli/Commands/SnapshotCommand.cs
  src/Bicep.Cli/Helpers/Snapshot/Snapshot.cs
  src/Bicep.Cli/Helpers/Snapshot/SnapshotDiffer.cs
  src/Bicep.Cli/Helpers/Snapshot/SnapshotHelper.cs
  src/Bicep.Cli/Rpc/CliJsonRpcServer.cs
  src/Bicep.Cli/Rpc/ICliJsonRpcProtocol.cs
  src/Bicep.Core.UnitTests/Mock/MockPublicModuleIndexHttpClient.cs
  src/Bicep.LangServer.IntegrationTests/LangServerScenarioTests.cs
Labels: 📘 Docs Needed

#17191 Write snapshot with indented JSON format
  src/Bicep.Cli.IntegrationTests/Files/SnapshotCommandTests/basic/main.bicep
  src/Bicep.Cli.IntegrationTests/Files/SnapshotCommandTests/basic/main.bicepparam
  src/Bicep.Cli.IntegrationTests/Files/SnapshotCommandTests/basic/main.snapshot.json
  src/Bicep.Cli.IntegrationTests/SnapshotCommandTests.cs
  src/Bicep.Cli/Commands/SnapshotCommand.cs
  src/Bicep.Cli/Helpers/Snapshot/Snapshot.cs
  src/Bicep.Cli/Helpers/Snapshot/SnapshotHelper.cs
Labels: 📘 Docs Not Needed

#17196 Enable decompilation of KV reference in parameters json
  src/Bicep.Cli.IntegrationTests/DecompileParamsCommandTests.cs
  src/Bicep.Decompiler.IntegrationTests/Files/Parameters/keyvaultreference/parameters.bicepparam
  src/Bicep.Decompiler.IntegrationTests/Files/Parameters/keyvaultreference/parameters.json
  src/Bicep.Decompiler.IntegrationTests/ParamsDecompilationTests.cs
  src/Bicep.Decompiler/BicepDecompiler.cs
  src/Bicep.LangServer.UnitTests/Handlers/BicepDecompileParamsCommandHandlerTests.cs
Labels: 📘 Docs Not Needed

#17195 Correct codegen for v1 local extensibility
  src/Bicep.Cli.IntegrationTests/Files/LocalDeployCommandTests/azure/bicepconfig.json
  src/Bicep.Cli.IntegrationTests/Files/LocalDeployCommandTests/azure/main.bicep
  src/Bicep.Cli.IntegrationTests/Files/LocalDeployCommandTests/azure/main.bicepparam
  src/Bicep.Cli.IntegrationTests/Files/LocalDeployCommandTests/azure/module.bicep
  src/Bicep.Cli.IntegrationTests/Files/LocalDeployCommandTests/weather/bicepconfig.json
  src/Bicep.Cli.IntegrationTests/Files/LocalDeployCommandTests/weather/main.bicep
  src/Bicep.Cli.IntegrationTests/Files/LocalDeployCommandTests/weather/main.bicepparam
  src/Bicep.Cli.IntegrationTests/LocalDeployCommandTests.cs
  src/Bicep.Cli/Commands/LocalDeployCommand.cs
  src/Bicep.Cli/Helpers/ServiceCollectionExtensions.cs
  src/Bicep.Cli/Program.cs
  src/Bicep.Core.UnitTests/Utils/RegistryHelper.cs
  src/Bicep.Core/Emit/TemplateWriter.cs
  src/Bicep.LangServer/Handlers/LocalDeployHandler.cs
  src/Bicep.LangServer/IServiceCollectionExtensions.cs
  src/Bicep.Local.Deploy.IntegrationTests/EndToEndDeploymentTests.cs
  src/Bicep.Local.Deploy/Azure/ArmDeploymentProvider.cs
  src/Bicep.Local.Deploy/Azure/IArmDeploymentProvider.cs
  src/Bicep.Local.Deploy/Engine/IServiceCollectionExtensions.cs
  src/Bicep.Local.Deploy/Engine/LocalDeploymentConfiguration.cs
  src/Bicep.Local.Deploy/Engine/LocalDeploymentEngine.cs
  src/Bicep.Local.Deploy/Engine/LocalDeploymentEngineHost.cs
  src/Bicep.Local.Deploy/Engine/LocalDeploymentSettings.cs
  src/Bicep.Local.Deploy/Engine/LocalEnablementConfigProvider.cs
  src/Bicep.Local.Deploy/Engine/LocalHttpContentHandler.cs
  src/Bicep.Local.Deploy/Engine/LocalKeyVaultDataProvider.cs
  src/Bicep.Local.Deploy/Engine/LocalRequestContext.cs
  src/Bicep.Local.Deploy/Engine/TraceEventSource.cs
  src/Bicep.Local.Deploy/Extensibility/GrpcLocalExtension.cs
  src/Bicep.Local.Deploy/Extensibility/GrpcLocalExtensionFactory.cs
  src/Bicep.Local.Deploy/Extensibility/ILocalExtension.cs
  src/Bicep.Local.Deploy/Extensibility/ILocalExtensionFactory.cs
  src/Bicep.Local.Deploy/Extensibility/LocalExtensionDispatcher.cs
  src/Bicep.Local.Deploy/Extensibility/LocalExtensionDispatcherFactory.cs
  src/Bicep.Local.Deploy/Extensibility/LocalExtensionOperationResponse.cs
  src/Bicep.Local.Deploy/Extensibility/NestedDeploymentExtension.cs
Labels: 📘 Docs Not Needed

#17198 Allow outer variable completions in user-defined functions
  src/Bicep.Core/Semantics/DeclarationVisitor.cs
  src/Bicep.Core/Semantics/NameBindingVisitor.cs
  src/Bicep.Core/Semantics/ScopeResolution.cs
  src/Bicep.LangServer.IntegrationTests/CompletionTests.cs
  src/Bicep.LangServer/Completions/BicepCompletionProvider.cs
Labels: 📘 Docs Not Needed

#17194 adding completion support for 'extends' keyword
  src/Bicep.LangServer.IntegrationTests/ParamsCompletionTests.cs
  src/Bicep.LangServer/Completions/BicepCompletionProvider.cs
Labels: 📘 Docs Not Needed

#17200 Handle case insensitive name clashes for imported variable, func, and type symbols
  src/Bicep.Core.IntegrationTests/ScenarioTests.cs
  src/Bicep.Core/Emit/EmitLimitationCalculator.cs
Labels: 📘 Docs Not Needed

#17201 Add value bounds to loop index variable
  src/Bicep.Core.IntegrationTests/ScenarioTests.cs
  src/Bicep.Core.Samples/Files/baselines/InvalidVariables_LF/main.symbols.bicep
  src/Bicep.Core.Samples/Files/baselines/LoopsIndexed_LF/main.symbols.bicep
  src/Bicep.Core/TypeSystem/TypeAssignmentVisitor.cs
Labels: 📘 Docs Not Needed

#17202 Raise error diagnostic on ambiguous scope
  src/Bicep.Core.IntegrationTests/ScenarioTests.cs
  src/Bicep.Core/Diagnostics/DiagnosticBuilder.cs
  src/Bicep.Core/Emit/ScopeHelper.cs
Labels: 📘 Docs Not Needed

#17232 Capture stderr in test logs to troubleshoot race condition
  src/Bicep.Cli.IntegrationTests/LocalDeployCommandTests.cs
Labels: 📘 Docs Not Needed

#17233 Add module identity snippets
  src/Bicep.LangServer.UnitTests/Snippets/SnippetsProviderTests.cs
  src/Bicep.LangServer/Completions/BicepCompletionProvider.cs
  src/Bicep.LangServer/Snippets/ISnippetsProvider.cs
  src/Bicep.LangServer/Snippets/SnippetsProvider.cs
Labels: 📘 Docs Not Needed

#17234 Fix local deploy for async operations
  src/Bicep.Cli.IntegrationTests/LocalDeployCommandTests.cs
  src/Bicep.Cli.IntegrationTests/packages.lock.json
  src/Bicep.Cli.UnitTests/packages.lock.json
  src/Bicep.Cli/Helpers/Snapshot/SnapshotHelper.cs
  src/Bicep.Cli/packages.lock.json
  src/Bicep.Core.IntegrationTests/Bicep.Core.IntegrationTests.csproj
  src/Bicep.Core.IntegrationTests/packages.lock.json
  src/Bicep.Core.Samples/packages.lock.json
  src/Bicep.Core.UnitTests/packages.lock.json
  src/Bicep.Core/Bicep.Core.csproj
  src/Bicep.Core/packages.lock.json
  src/Bicep.Decompiler.IntegrationTests/packages.lock.json
  src/Bicep.Decompiler.UnitTests/packages.lock.json
  src/Bicep.Decompiler/packages.lock.json
  src/Bicep.LangServer.IntegrationTests/packages.lock.json
  src/Bicep.LangServer.UnitTests/packages.lock.json
  src/Bicep.LangServer/packages.lock.json
  src/Bicep.Local.Deploy.IntegrationTests/packages.lock.json
  src/Bicep.Local.Deploy/Bicep.Local.Deploy.csproj
  src/Bicep.Local.Deploy/packages.lock.json
  src/Bicep.Local.Extension.Mock/packages.lock.json
  src/Bicep.RegistryModuleTool.IntegrationTests/packages.lock.json
  src/Bicep.RegistryModuleTool.TestFixtures/packages.lock.json
  src/Bicep.RegistryModuleTool.UnitTests/packages.lock.json
  src/Bicep.RegistryModuleTool/packages.lock.json
  src/Bicep.Tools.Benchmark/packages.lock.json
  src/Bicep.Wasm/packages.lock.json
Labels: 📘 Docs Not Needed
